media:
  input: /public
  output: /
content:
  - name: index
    label: Homepage
    type: file
    path: src/content/index.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxLength: 100 } }
      - { name: landing, component: landing }
      - name: sections
        label: Sections
        list: true
        component: section
      - { name: body, label: Body, type: rich-text }
  - name: footer
    label: Footer
    type: file
    path: src/content/footer.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
      - { name: social_links, label: Social Links, component: social_links, list: true }
components:
  landing:
    label: Landing Section
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: Subtitle
        type: rich-text
  section:
    label: Section
    fields:
      - name: title
        label: Section title
        type: string
      - name: body
        label: Section content
        type: rich-text
  social_links:
    label: Social Link
    fields:
      - name: name
        label: Name
        type: string
      - name: link
        label: Link
        type: string
      - name: icon
        label: Link Icon
        type: image
