import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ReactMarkdown from "react-markdown";
import Markdown from "@/lib/markdown";
import remarkDirective from "remark-directive";
import remarkParseDirective from "@/lib/remark-parse-directive";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = Markdown.getLayout("/");

  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactMarkdown
          remarkPlugins={[remarkDirective, remarkParseDirective]}
          components={{
            // @ts-expect-error Custom components
            navbar: Navbar,
            footer: Footer,
            slot: () => children,
          }}
        >
          {content}
        </ReactMarkdown>
      </body>
    </html>
  );
}
